### ISSUE TITLE
GPU and Cudnn not detected - very slow program

### ISSUE THREAD

**Issue by Flodkozza** [Orinion/YOLOLA#1]
My gpu and cudnn arent detected even I obviously havr them and they are detected when I use darknet. How can I fix this?

**Comment by Orinion** [comment]
sorry but i don't know either

**Comment by Flodkozza** [comment]
I fixed it by uninstalling CUDA and installing it again.

**Comment by Flodkozza** [comment]
I fixed it by uninstalling CUDA and installing it again.
